<a href="https://colab.research.google.com/github/NileshPatil24-a/Complete_DataScience_Revision/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [5]:
# series
label = ['a','b','c']
numer = [10,20,30]
arr = np.array([12,3,4,5])
dict = {'a':3, 'e':4, 2:4}

pd.Series(label, name='char')

0    a
1    b
2    c
Name: age, dtype: object

In [7]:
pd.Series(dict, name='numbers')

a    3
e    4
2    4
Name: numbers, dtype: int64